### PR TITLE
backdrop-contrib/devel #4: Add access to core's theme debug and watchdog filter settings.

### PR DESCRIPTION
**Pull request by ghost**
Fixes backdrop-contrib/devel#4 and provides similar support for backdrop/backdrop-issues#1568.

Replaces PR backdrop-contrib/devel#11

### CODE REVIEW

**Comment by klonos** [comment]
...from https://github.com/backdrop-contrib/devel/pull/11#issuecomment-216044468

> In my head, headers look like titles to me, so they get title case,

If by "headers" you are referring to fieldset labels, then yes, they are rendered in uppercase, but that is only through the use of CSS `text-transform`. The actual text is sentence case.

If you are referring to the labels of checkbox or radio button sets, then the way we make them stick out in the UI is by rendering them in bold text. Now, I noticed that the "Watchdog severity levels" label for example is not rendered in bold. This is because we have a CSS rule in the core Seven theme that overrides the bold text for labels within fieldsets and renders those with normal weight. But I think that this must be a bug (https://github.com/backdrop/backdrop-issues/issues/1828).

> ...and "theme debug" feels like a proper name of a feature.

AFAIK, we do not capitalize features. For example we have "Put site into maintenance mode" (we do not capitalize "maintenance mode"). Do you have any examples of such cases in the UI or any help text?

Anyways, thank you for the prompt corrections of the code. I got this error when I applied your changes in a local dev:

```
Warning: Invalid argument supplied for foreach() in C:\www\core\includes\form.inc on line 2400
Call Stack
#   Time    Memory   Function  Location
1   0.0004  243232   {main}( )                                                                 ...\index.php:0
2   0.1507  2371664  menu_execute_active_handler( )                                            ...\index.php:21
3   0.1514  2372536  layout_route_handler( )                                                   ...\menu.inc:524
4   0.1631  2774872  LayoutRendererStandard->render( )                                         ...\layout.module:450
5   0.1632  2777280  LayoutRendererStandard->renderLayout( )                                   ...\layout_renderer_standard.inc:312
6   0.1662  2795392  LayoutRendererStandard->renderBlocks( )                                   ...\layout_renderer_standard.inc:331
7   0.1662  2796256  LayoutRendererStandard->renderBlock( )                                    ...\layout_renderer_standard.inc:408
8   0.1662  2796336  BlockLegacy->getContent( )                                                ...\layout_renderer_standard.inc:450
9   0.1662  2796472  BlockLegacy->buildBlock( )                                                ...\block_legacy.class.inc:57
10  0.1662  2797272  module_invoke( )                                                          ...\block_legacy.class.inc:30
11  0.1663  2797856  call_user_func_array:{C:\www\core\includes\module.inc:913} ( )            ...\module.inc:913
12  0.1663  2798448  system_block_view( )                                                      ...\module.inc:913
13  0.1678  2802880  call_user_func_array:{C:\www\core\modules\system\system.module:2318} ( )  ...\system.module:2318
14  0.1678  2803248  backdrop_get_form( )                                                      ...\system.module:2318
15  0.1679  2804128  backdrop_build_form( )                                                    ...\form.inc:131
16  0.1990  2943808  backdrop_process_form( )                                                  ...\form.inc:385
17  0.1990  2946856  form_builder( )                                                           ...\form.inc:894
18  0.1994  2953120  form_builder( )                                                           ...\form.inc:1935
19  0.2004  2963400  form_builder( )                                                           ...\form.inc:1935
20  0.2007  2964512  _form_builder_handle_input_element( )                                     ...\form.inc:1873
21  0.2007  2968576  form_type_checkboxes_value( )                                             ...\form.inc:2137
```

**Comment by sentaidigital** [comment]
Ah... yes.  It's looking for the `watchdog_enabled_severity_levels` defined in backdrop/backdrop#1304 (a PR for backdrop/backdrop-issues#1568).

We have three options here:
1. Wait for PR backdrop/backdrop#1304 to be merged before we retest & merge this PR.
2. Update this patch to look for a NULL result from $config->get('watchdog_enabled_severity_levels') and hide the setting.
3. Split it into two patches, both with a fieldset form element, or one depending on the other.

I'd prefer option 1 as that requires the least amount of patch management on my part.  What are the odds we can get backdrop/backdrop-issues#1568 into the 1.4 release?

**Comment by klonos** [comment]
I'd say go with option 1 but make sure you do not make a new release until the core patch is merged because that would then introduce a bug. No harm if the change is merged in the 1.x branch (dev) without actually being in an official release.

**Comment by quicksketch** [comment]
Hm, yeah I'd love to merge this in for the theme_debug mode but the `watchdog_enabled_severity_levels` isn't yet merged into Backdrop core itself. Even if it were, it seems like we should check if it is supported before trying to set a value for it (for sites using older versions of Backdrop core).

**Comment by sentaidigital** [comment]
Is there anyway to set this "needs review"?

**Comment by klonos** [comment]
@sentaidigital I have permissions to change issue labels (what GitHub calls its issue tags), but contrib does not have the same labels as core available (although IIRC we did have an issue filed somewhere where @Gormartsen would try to get labels to sync across all backdrop\* repos).

**Comment by quicksketch** [comment]
My merging of https://github.com/backdrop-contrib/devel/pull/28 caused a conflict here. I'll pull out the code from here and merge it together.

**Comment by quicksketch** [comment]
I did some additional rearrangement of the UI in the merge. Commit is at https://github.com/backdrop-contrib/devel/commit/49a1f79ae486dd09486ab3ff9e6c7570d9201a9a. Thanks @sentaidigital for your work here!

**Pull request closed without merging**
